export const enterprise = {
  brand: 'Nexus Research',
  tagline: 'Governed data and reproducible analysis for research teams.',
  links: [
    { label: 'Platform', href: '#platform' },
    { label: 'Lineage', href: '#lineage' },
    { label: 'Security', href: '#security' },
    { label: 'Compare', href: '#compare' },
    { label: 'FAQ', href: '#faq' },
  ],
  cta: { label: 'Book a demo', href: '#contact' },
  features: [
    { icon: 'Database', title: 'Governed datasets', description: 'Versioned data with lineage, access policies and retention controls.' },
    { icon: 'FileText', title: 'Reproducible runs', description: 'Every analysis records code, parameters and data versions so results can be re-created.' },
    { icon: 'Users', title: 'Team workspaces', description: 'Projects, roles and review workflows that mirror how your organisation works.' },
    { icon: 'ShieldCheck', title: 'Audit everything', description: 'Immutable activity records for access, exports and configuration changes.' },
    { icon: 'KeyRound', title: 'Single sign-on', description: 'SAML and OIDC with group-to-role mapping and enforced multi-factor authentication.' },
    { icon: 'Cpu', title: 'Scalable compute', description: 'Queue-based jobs with quotas, priorities and cost reporting per project.' },
  ],
  stats: [
    { value: '120+', label: 'institutions' },
    { value: '2.4M', label: 'runs archived' },
    { value: '99.95%', label: 'uptime' },
    { value: '24/7', label: 'support' },
  ],
  comparison: {
    columns: ['Spreadsheets and scripts', 'Nexus Research'],
    rows: [
      ['Versioned data and lineage', 'No', 'Yes'],
      ['Role-based access and review', 'Partial', 'Yes'],
      ['Audit trail of exports', 'No', 'Yes'],
      ['Reproducible runs', 'Manual', 'Automatic'],
      ['Single sign-on', 'No', 'Yes'],
    ],
  },
  testimonials: [
    { quote: 'Reproducibility used to be a heroic effort. Now it is the default.', name: 'Dr. Elif Kaya', role: 'Director, Data Science Institute' },
    { quote: 'Our compliance office finally has a single place to review access and exports.', name: 'Henrik Larsen', role: 'CISO, Meridian Health' },
    { quote: 'Onboarding new researchers dropped from weeks to a day.', name: 'Priya Singh', role: 'Research Operations Lead' },
  ],
  faq: [
    { q: 'Can we deploy in our own environment?', a: 'Yes. A containerised deployment is available for private cloud and on-premises installations.' },
    { q: 'How is access controlled?', a: 'Through roles and project permissions, with SSO and enforced multi-factor authentication on request.' },
    { q: 'What happens to our data if we leave?', a: 'You can export datasets, runs and the full audit trail in open formats.' },
  ],
  sections: [
    { id: 'platform', label: 'Platform' },
    { id: 'lineage', label: 'Data lineage' },
    { id: 'cases', label: 'Case studies' },
    { id: 'security', label: 'Security and compliance' },
    { id: 'compare', label: 'Comparison' },
    { id: 'onboarding', label: 'Onboarding' },
    { id: 'faq', label: 'FAQ' },
  ],
  institutions: [
    'Northgate University', 'Meridian Health', 'Aalto Institute of Data', 'Helix Genomics', 'Lakeland Research Council',
    'Orchard Statistics Office', 'Baltic Climate Lab', 'Fenwick Medical School', 'Polar Observatory Network', 'Kestrel Policy Centre',
  ],
  proof: ['Versioned data with full lineage', 'Every run re-creatable from one record', 'Access reviewed and exported on the record'],
  countStats: [
    { value: 120, suffix: '+', label: 'research institutions', note: 'across universities, hospitals and public bodies' },
    { value: 2.4, suffix: 'M', decimals: 1, label: 'runs archived', note: 'each one re-creatable from its record' },
    { value: 99.95, suffix: '%', decimals: 2, label: 'uptime over 12 months', note: 'measured on the public status page' },
    { value: 14, suffix: ' days', label: 'to first reproduced result', note: 'median across new deployments' },
  ],
  lineage: {
    title: 'Follow every result back to its source',
    description: 'Each figure in a paper links to the run that produced it, the code that ran and the exact data versions it read. Nothing is reconstructed from memory.',
    nodes: [
      { id: 'raw', label: 'Source data', description: 'Instruments, registries and partner feeds are ingested and checksummed.', x: 8, y: 50, tone: 'info' as const },
      { id: 'clean', label: 'Curated dataset', description: 'Cleaning steps are versioned, reviewed and recorded.', x: 33, y: 22, tone: 'primary' as const },
      { id: 'run', label: 'Analysis run', description: 'Code, parameters and environment are captured automatically.', x: 33, y: 78, tone: 'primary' as const },
      { id: 'review', label: 'Peer review', description: 'Reviewers inspect the run and sign off in the workspace.', x: 62, y: 50, tone: 'success' as const },
      { id: 'publish', label: 'Published result', description: 'Figures, tables and the audit trail are exported together.', x: 91, y: 50, tone: 'accent' as const },
    ],
    edges: [
      { from: 'raw', to: 'clean', label: 'is curated into' },
      { from: 'raw', to: 'run', label: 'feeds' },
      { from: 'clean', to: 'review', label: 'is reviewed in' },
      { from: 'run', to: 'review', label: 'is reviewed in' },
      { from: 'review', to: 'publish', label: 'is released as' },
    ],
  },
  cases: [
    { quote: 'Reproducibility used to be a heroic effort. Now it is the default, and reviewers stopped asking us to re-run things by hand.', name: 'Dr. Elif Kaya', role: 'Director, Data Science Institute', org: 'Northgate University', metric: '4x', metricLabel: 'faster peer review turnaround' },
    { quote: 'Our compliance office finally has a single place to review access and exports, with a record they trust.', name: 'Henrik Larsen', role: 'CISO', org: 'Meridian Health', metric: '100%', metricLabel: 'of data exports reviewed and logged' },
    { quote: 'Onboarding new researchers dropped from weeks to a day, because the environment and the data come ready.', name: 'Priya Singh', role: 'Research Operations Lead', org: 'Helix Genomics', metric: '1 day', metricLabel: 'to a productive workspace' },
  ],
  security: [
    { icon: 'ShieldCheck', title: 'Immutable audit trail', description: 'Access, exports and configuration changes are written to an append-only record.', tag: 'Audit' },
    { icon: 'KeyRound', title: 'SSO and enforced MFA', description: 'SAML and OIDC with group-to-role mapping and mandatory multi-factor sign-in.', tag: 'Identity' },
    { icon: 'Lock', title: 'Encryption everywhere', description: 'Data is encrypted in transit and at rest, with customer-managed keys available.', tag: 'Data' },
    { icon: 'Server', title: 'Your environment', description: 'Deploy in private cloud or on premises with a containerised distribution.', tag: 'Hosting' },
    { icon: 'FileText', title: 'Retention policies', description: 'Set retention and legal-hold rules per dataset and enforce them automatically.', tag: 'Governance' },
    { icon: 'Users', title: 'Least-privilege roles', description: 'Project-scoped roles with time-boxed access and periodic access reviews.', tag: 'Access' },
  ],
  onboarding: [
    { date: 'Week 1', title: 'Connect and map', description: 'Link identity providers and data sources, then map groups to roles with your security team.' },
    { date: 'Week 2', title: 'Import and version', description: 'Bring in existing datasets and notebooks. Lineage is reconstructed where history allows.' },
    { date: 'Week 3', title: 'Reproduce a flagship result', description: 'Re-create a published analysis end to end to confirm the platform meets your standard.' },
    { date: 'Week 4', title: 'Open to every team', description: 'Roll out workspaces, review workflows and training to the wider organisation.' },
  ],
};
