import { type ThemePreset } from './modern-saas';

export const aiFuturisticPreset: ThemePreset = {
  id: 'ai-futuristic',
  name: 'AI Futuristic',
  description: 'Deep obsidian canvas, luminescent violet & cyan neon accents, and expressive dynamic animation.',
  fontFamily: 'Manrope',
  radius: 'medium',
  density: 'comfortable',
  motion: 'expressive',
  colors: {
    light: {
      canvas: '#f5f3ff',
      surface: '#ffffff',
      surfaceElevated: '#ffffff',
      border: '#e9d5ff',
      text: '#1e1b4b',
      textMuted: '#5a606c',
      primary: '#7637e1',
      primaryForeground: '#ffffff',
      secondary: '#0284c7',
      secondaryForeground: '#0b0f19',
      accent: '#046b7d',
      accentForeground: '#ffffff',
      success: '#0a6f4d',
      successForeground: '#ffffff',
      warning: '#885806',
      warningForeground: '#ffffff',
      danger: '#b02e44',
      dangerForeground: '#ffffff',
      info: '#6e49c3',
      infoForeground: '#ffffff',
    },
    dark: {
      canvas: '#05050a',
      surface: '#0d0d17',
      surfaceElevated: '#161626',
      border: '#272343',
      text: '#f3f4f6',
      textMuted: '#a1a1aa',
      primary: '#a079f7',
      primaryForeground: '#0b0f19',
      secondary: '#1e1e38',
      secondaryForeground: '#ffffff',
      accent: '#06b6d4',
      accentForeground: '#0b0f19',
      success: '#34d399',
      successForeground: '#0b0f19',
      warning: '#fbbf24',
      warningForeground: '#0b0f19',
      danger: '#fb7185',
      dangerForeground: '#0b0f19',
      info: '#a78bfa',
      infoForeground: '#0b0f19',
    },
  },
};
