import { type ThemePreset } from './modern-saas';

export const appleInspiredPreset: ThemePreset = {
  id: 'apple-inspired',
  name: 'Apple Inspired',
  description: 'Spacious editorial hierarchy, OLED blacks, pure white surfaces, and subtle precision typography.',
  fontFamily: 'Geist',
  radius: 'large',
  density: 'spacious',
  motion: 'standard',
  colors: {
    light: {
      canvas: '#f5f5f7',
      surface: '#ffffff',
      surfaceElevated: '#ffffff',
      border: '#e5e5ea',
      text: '#1d1d1f',
      textMuted: '#5f5f63',
      primary: '#0060bf',
      primaryForeground: '#ffffff',
      secondary: '#1d1d1f',
      secondaryForeground: '#ffffff',
      accent: '#1e6b79',
      accentForeground: '#ffffff',
      success: '#1e7032',
      successForeground: '#ffffff',
      warning: '#8f5400',
      warningForeground: '#ffffff',
      danger: '#b62a22',
      dangerForeground: '#ffffff',
      info: '#0060bf',
      infoForeground: '#ffffff',
    },
    dark: {
      canvas: '#000000',
      surface: '#161617',
      surfaceElevated: '#242426',
      border: '#2c2c2e',
      text: '#f5f5f7',
      textMuted: '#aaaaad',
      primary: '#41a2ff',
      primaryForeground: '#0b0f19',
      secondary: '#3a3a3c',
      secondaryForeground: '#ffffff',
      accent: '#64d2ff',
      accentForeground: '#0b0f19',
      success: '#30d158',
      successForeground: '#0b0f19',
      warning: '#ffd60a',
      warningForeground: '#0b0f19',
      danger: '#ff6e65',
      dangerForeground: '#0b0f19',
      info: '#41a2ff',
      infoForeground: '#0b0f19',
    },
  },
};
