import { type ThemePreset } from './modern-saas';

export const dataDensePreset: ThemePreset = {
  id: 'data-dense',
  name: 'Data Dense',
  description: 'Compact information architecture, high-contrast borders, minimal distraction, and rapid operational glanceability.',
  fontFamily: 'IBM Plex Sans',
  radius: 'small',
  density: 'compact',
  motion: 'minimal',
  colors: {
    light: {
      canvas: '#f4f4f5',
      surface: '#ffffff',
      surfaceElevated: '#ffffff',
      border: '#d4d4d8',
      text: '#18181b',
      textMuted: '#52525b',
      primary: '#02669a',
      primaryForeground: '#ffffff',
      secondary: '#27272a',
      secondaryForeground: '#ffffff',
      accent: '#036f4d',
      accentForeground: '#ffffff',
      success: '#0f7032',
      successForeground: '#ffffff',
      warning: '#935104',
      warningForeground: '#ffffff',
      danger: '#b81f1f',
      dangerForeground: '#ffffff',
      info: '#02669a',
      infoForeground: '#ffffff',
    },
    dark: {
      canvas: '#09090b',
      surface: '#121215',
      surfaceElevated: '#1c1c22',
      border: '#27272a',
      text: '#fafafa',
      textMuted: '#a1a1aa',
      primary: '#38bdf8',
      primaryForeground: '#0b0f19',
      secondary: '#27272a',
      secondaryForeground: '#ffffff',
      accent: '#10b981',
      accentForeground: '#0b0f19',
      success: '#22c55e',
      successForeground: '#0b0f19',
      warning: '#f59e0b',
      warningForeground: '#0b0f19',
      danger: '#f26666',
      dangerForeground: '#0b0f19',
      info: '#38bdf8',
      infoForeground: '#0b0f19',
    },
  },
};
