import { type ThemePreset } from './modern-saas';

export const professionalPreset: ThemePreset = {
  id: 'professional',
  name: 'Professional',
  description: 'Deep navy clarity, slate neutral surfaces, crisp borders, and restrained executive motion.',
  fontFamily: 'Inter',
  radius: 'small',
  density: 'comfortable',
  motion: 'minimal',
  colors: {
    light: {
      canvas: '#f1f5f9',
      surface: '#ffffff',
      surfaceElevated: '#ffffff',
      border: '#cbd5e1',
      text: '#0f172a',
      textMuted: '#475569',
      primary: '#1e40af',
      primaryForeground: '#ffffff',
      secondary: '#334155',
      secondaryForeground: '#ffffff',
      accent: '#2158d1',
      accentForeground: '#ffffff',
      success: '#036f4d',
      successForeground: '#ffffff',
      warning: '#935104',
      warningForeground: '#ffffff',
      danger: '#ba2020',
      dangerForeground: '#ffffff',
      info: '#02679c',
      infoForeground: '#ffffff',
    },
    dark: {
      canvas: '#090d16',
      surface: '#0f172a',
      surfaceElevated: '#1e293b',
      border: '#334155',
      text: '#f1f5f9',
      textMuted: '#99a8bc',
      primary: '#74a6f9',
      primaryForeground: '#0b0f19',
      secondary: '#475569',
      secondaryForeground: '#ffffff',
      accent: '#65a8fa',
      accentForeground: '#0b0f19',
      success: '#12ba82',
      successForeground: '#0b0f19',
      warning: '#f59e0b',
      warningForeground: '#0b0f19',
      danger: '#f48080',
      dangerForeground: '#0b0f19',
      info: '#38bdf8',
      infoForeground: '#0b0f19',
    },
  },
};
